name: Makefile Lint

on:
  push:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2 
    - name: install
      run: make install
    - name: lint
      run: make lint
